export type TableEntry = { value: string | number; label: string };

export const TABLE_OPTIONS: Record<string, TableEntry[]> = {
  'Periodic Check': [
    { value: 'continue', label: 'Passage continues' },
    { value: 'turn', label: 'Passage turns' },
    { value: 'door', label: 'Door' },
    { value: 'side_passage', label: 'Side passage' },
    { value: 'chamber', label: 'Chamber or Room' },
    { value: 'dead_end', label: 'Dead end' },
  ],
  'Turn Type': [
    { value: 'left_90', label: 'Left 90°' },
    { value: 'right_90', label: 'Right 90°' },
    { value: 'left_45_ahead', label: 'Left 45° ahead' },
    { value: 'right_45_ahead', label: 'Right 45° ahead' },
    { value: 'y_intersection', label: 'Y intersection' },
    { value: 't_intersection', label: 'T intersection' },
    { value: 'x_intersection', label: 'X intersection' },
  ],
  'Side Passage': [
    { value: 'left', label: 'Left' },
    { value: 'right', label: 'Right' },
    { value: 'both', label: 'Both sides' },
    { value: 'ahead_left_right', label: 'Ahead, left and right' },
    { value: 'passage_t', label: "Passage T's" },
  ],
  'Passage Width': [
    { value: '1', label: '5 ft' },
    { value: '2', label: '10 ft' },
    { value: '4', label: '20 ft' },
    { value: '6', label: '30 ft' },
    { value: '0', label: 'Special' },
  ],
  'Room Shape': [
    { value: 'square', label: 'Square' },
    { value: 'rectangle', label: 'Rectangle' },
    { value: 'circle', label: 'Circle' },
    { value: 'irregular', label: 'Irregular' },
  ],
  'Room Width': [
    { value: '2', label: '20 ft' },
    { value: '3', label: '30 ft' },
    { value: '4', label: '40 ft' },
    { value: '5', label: '50 ft' },
    { value: '6', label: '60 ft' },
    { value: '8', label: '80 ft' },
    { value: '10', label: '100 ft' },
  ],
  'Room Depth': [
    { value: '2', label: '20 ft' },
    { value: '3', label: '30 ft' },
    { value: '4', label: '40 ft' },
    { value: '5', label: '50 ft' },
    { value: '6', label: '60 ft' },
    { value: '8', label: '80 ft' },
    { value: '10', label: '100 ft' },
  ],
  'Room Contents': [
    { value: 'empty', label: 'Empty' },
    { value: 'monster', label: 'Monster' },
    { value: 'monster_treasure', label: 'Monster with Treasure' },
    { value: 'trap', label: 'Trap' },
    { value: 'trap_treasure', label: 'Trap with Treasure' },
    { value: 'special', label: 'Special' },
    { value: 'treasure', label: 'Unguarded Treasure' },
  ],
  'Trap Type': [
    { value: 'pit', label: 'Pit' },
    { value: 'spiked_pit', label: 'Spiked pit' },
    { value: 'chute', label: 'Chute' },
    { value: 'teleporter', label: 'Teleporter' },
    { value: 'gas', label: 'Gas' },
    { value: 'flooding', label: 'Flooding room' },
    { value: 'ceiling_block', label: 'Ceiling block' },
    { value: 'dart', label: 'Dart trap' },
    { value: 'spear', label: 'Spear trap' },
    { value: 'pendulum_blade', label: 'Pendulum blade' },
    { value: 'rolling_rock', label: 'Rolling rock' },
    { value: 'portcullis_drop', label: 'Portcullis drop' },
  ],
  'Room Dressing': [
    { value: 'furnishings', label: 'Furnishings' },
    { value: 'debris', label: 'Debris' },
    { value: 'refuse', label: 'Refuse' },
    { value: 'shrine', label: 'Shrine' },
    { value: 'pool', label: 'Pool' },
    { value: 'statue', label: 'Statue' },
    { value: 'tapestry', label: 'Tapestry' },
    { value: 'writing', label: 'Writing on wall' },
    { value: 'bones', label: 'Bones' },
    { value: 'tracks', label: 'Tracks' },
    { value: 'smell', label: 'Smell' },
    { value: 'sound', label: 'Sound' },
  ],
  'Room Exits': [
    { value: '1', label: '1 exit' },
    { value: '2', label: '2 exits' },
    { value: '3', label: '3 exits' },
    { value: '4', label: '4 exits' },
  ],
  'Door Type': [
    { value: 'wooden', label: 'Wooden' },
    { value: 'wooden_locked', label: 'Wooden (locked)' },
    { value: 'wooden_stuck', label: 'Wooden (stuck)' },
    { value: 'stone', label: 'Stone' },
    { value: 'stone_secret', label: 'Stone (secret)' },
    { value: 'iron', label: 'Iron' },
    { value: 'portcullis', label: 'Portcullis' },
    { value: 'archway', label: 'Archway (no door)' },
  ],
  'Exit Door': [
    { value: 'wooden', label: 'Wooden' },
    { value: 'wooden_locked', label: 'Wooden (locked)' },
    { value: 'wooden_stuck', label: 'Wooden (stuck)' },
    { value: 'stone', label: 'Stone' },
    { value: 'stone_secret', label: 'Stone (secret)' },
    { value: 'iron', label: 'Iron' },
    { value: 'portcullis', label: 'Portcullis' },
    { value: 'archway', label: 'Archway (no door)' },
  ],
};
